DEFN_SYSCALL1(kprint, 0, const char*);
DEFN_SYSCALL0(fork, 1);
DEFN_SYSCALL0(getpid, 2);
DEFN_SYSCALL0(pause, 3);
DEFN_SYSCALL1(exit, 4, int);
DEFN_SYSCALL1(sleep, 5, int);
DEFN_SYSCALL1(wait_any, 6, int*);
DEFN_SYSCALL2(open, 7, const char*, int);
DEFN_SYSCALL3(read, 8, int, char*, int);
DEFN_SYSCALL3(mount, 9, const char*, const char*, const char*);
DEFN_SYSCALL3(seek, 10, int, int, int);
DEFN_SYSCALL3(write, 11, int, char*, int);
DEFN_SYSCALL1(sbrk, 12, int);
DEFN_SYSCALL3(getdents, 13, int, void*, int);
DEFN_SYSCALL2(channel_connect, 14, int, int);
DEFN_SYSCALL0(channel_create, 15);
DEFN_SYSCALL3(msg_recv, 16, int, void*, int);
DEFN_SYSCALL3(writev, 19, int, struct iovec*, int);
DEFN_SYSCALL3(ioctl, 20, int, unsigned long, unsigned long);
DEFN_SYSCALL1(brk, 21, u32);
DEFN_SYSCALL1(dup, 22, int);
DEFN_SYSCALL1(set_thread_area, 23, struct region*);
DEFN_SYSCALL4(rt_sigprocmask, 24, int, void*, void*, int);
DEFN_SYSCALL1(set_tid_address, 25, int*);
DEFN_SYSCALL2(kill, 26, int, int);
DEFN_SYSCALL0(getpgrp, 27);
DEFN_SYSCALL2(stat, 28, char*, struct stat*);
DEFN_SYSCALL0(geteuid, 29);
DEFN_SYSCALL1(getppid, 30, int);
DEFN_SYSCALL2(getcwd, 31, char*, int);
DEFN_SYSCALL4(rt_sigaction, 32, int, void*, void*, int);
DEFN_SYSCALL3(fcntl, 33, int, int, void*);
DEFN_SYSCALL1(close, 34, int);
